In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/My Drive/dataset/heart.csv")
df.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [3]:
df2 = df[(df['age']>40)&(df['age']<50)]
df2

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
8      46    1   0       120   249    0        0      144      0      0.8   
11     43    0   0       132   341    1        0      136      1      3.0   
22     45    1   0       104   208    0        0      148      1      3.0   
24     42    0   2       120   209    0        1      173      0      0.0   
26     44    1   2       130   233    0        1      179      1      0.4   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1012   48    1   1       110   229    0        1      168      0      1.0   
1014   44    0   2       108   141    0        1      175      0      0.6   
1018   41    1   0       110   172    0        0      158      0      0.0   
1019   47    1   0       112   204    0        1      143      0      0.1   
1022   47    1   0       110   275    0        0      118      1      1.0   

      slope  ca  thal  target  
8         2   0     3       0  
11        1   0     3       0  
22        1   0     2       1  
24        1   0     2       1  
26        2   0     2       1  
...     ...  ..   ...     ...  
1012      0   0     3       0  
1014      1   0     2       1  
1018      2   0     3       0  
1019      2   0     2       1  
1022      1   1     2       0  

[226 rows x 14 columns]

In [4]:
x = df.iloc[:,0:13]
y = df.iloc[:,13]

x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [5]:
x = df.iloc[:,0:13]
y = df.iloc[:,13]

y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.1)

x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
800   67    1   0       120   229    0        0      129      1      2.6   
474   48    1   1       110   229    0        1      168      0      1.0   
997   54    1   0       120   188    0        1      113      0      1.4   
925   57    1   0       130   131    0        1      115      1      1.2   
481   63    0   0       150   407    0        0      154      0      4.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
673   54    1   2       120   258    0        0      147      0      0.4   
770   41    1   1       135   203    0        1      132      0      0.0   
744   60    0   2       102   318    0        1      160      0      0.0   
18    50    0   1       120   244    0        1      162      0      1.1   
316   64    0   2       140   313    0        1      133      0      0.2   

     slope  ca  thal  
800      1   2     3  
474      0   0     3  
997      1   1     3  
925      1   1     3  
481      1   3     3  
..     ...  ..   ...  
673      1   0     3  
770      1   0     1  
744      2   1     2  
18       2   0     2  
316      2   0     3  

[922 rows x 13 columns]

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.1)

y_train

791     0
729     1
114     0
486     0
724     1
       ..
233     1
324     1
1001    1
610     0
566     1
Name: target, Length: 922, dtype: int64

In [8]:
from sklearn.svm import SVC

clf =SVC()
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

y_pred

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [11]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred, y_test))

0.6310679611650486


In [12]:
predictions = clf.predict(x_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))


[[30 28]
 [10 35]]


In [13]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.75      0.52      0.61        58
           1       0.56      0.78      0.65        45

    accuracy                           0.63       103
   macro avg       0.65      0.65      0.63       103
weighted avg       0.67      0.63      0.63       103



In [14]:
param_grid = {'C': [0.001,0.01,0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=3)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 35 candidates, totalling 175 fits
[CV 1/5] END ......C=0.001, gamma=1, kernel=rbf;, score=0.519 total time=   0.0s
[CV 2/5] END ......C=0.001, gamma=1, kernel=rbf;, score=0.524 total time=   0.0s
[CV 3/5] END ......C=0.001, gamma=1, kernel=rbf;, score=0.522 total time=   0.0s
[CV 4/5] END ......C=0.001, gamma=1, kernel=rbf;, score=0.522 total time=   0.0s
[CV 5/5] END ......C=0.001, gamma=1, kernel=rbf;, score=0.522 total time=   0.0s
[CV 1/5] END ....C=0.001, gamma=0.1, kernel=rbf;, score=0.519 total time=   0.1s
[CV 2/5] END ....C=0.001, gamma=0.1, kernel=rbf;, score=0.524 total time=   0.0s
[CV 3/5] END ....C=0.001, gamma=0.1, kernel=rbf;, score=0.522 total time=   0.0s
[CV 4/5] END ....C=0.001, gamma=0.1, kernel=rbf;, score=0.522 total time=   0.1s
[CV 5/5] END ....C=0.001, gamma=0.1, kernel=rbf;, score=0.522 total time=   0.0s
[CV 1/5] END ...C=0.001, gamma=0.01, kernel=rbf;, score=0.519 total time=   0.0s
[CV 2/5] END ...C=0.001, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [15]:
grid.best_params_

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}

In [16]:
grid.best_estimator_

SVC(C=1, gamma=1)

In [17]:
grid_predictions = grid.predict(x_test)

print(confusion_matrix(y_test,grid_predictions))

[[58  0]
 [ 0 45]]


In [18]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        58
           1       1.00      1.00      1.00        45

    accuracy                           1.00       103
   macro avg       1.00      1.00      1.00       103
weighted avg       1.00      1.00      1.00       103



In [19]:
test_index = 1

test_dic = {0:'No Heart Disease', 1: 'Heart Disease'}
y_test_np = np.array(y_test)
print(f'Actual     --> {test_dic[y_test_np[test_index]]}\nPrediction --> {test_dic[predictions[test_index]]}')

Actual     --> No Heart Disease
Prediction --> Heart Disease
